<?php

function pastry_quiz_menu() {
    $items['quiz'] = array(
        'title' => 'What baked goods should I eat!?',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('quiz1_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['quiz_question_2'] = array(
        'page callback' => 'drupal_get_form',
        'page arguments' => array('quiz2_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['quiz_question_3'] = array(
        'page callback' => 'drupal_get_form',
        'page arguments' => array('quiz3_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['quiz_results'] = array(
        'title' => 'Quiz Results!',
        'page callback' => 'quiz_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function quiz1_form() {
  $form['fruit'] = array(
    '#title' => 'Do You like Fruit?',
    '#type' => 'radios',
    '#description' => t(''),
    '#default_value' => variable_get('comment_preview', 0),
    '#options' => array(
      t('Yes'),
      t('No'),
    ),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
  );
  return $form;
}


function quiz2_form() {
  $form['chocolate'] = array(
      '#title' => 'Do you want chocolate?',
      '#type' => 'radios',
      '#description' => t('Chocoholic?'),
      '#default_value' => variable_get('comment_preview', 0),
      '#options' => array(
          t('Yes'),
          t('No'),
      ),
      '#required' => TRUE,
  );
  $form['submit'] = array(
          '#type' => 'submit',
          '#value' => 'submit',
  );
  return $form;
}


function quiz3_form() {
  $form['gluten'] = array(
      '#title' => 'Are you gluten intollerant?',
      '#type' => 'radios',
      '#description' => t('Got wheat?'),
      '#default_value' => variable_get('comment_preview', 0),
      '#options' => array(
          t('Yes'),
          t('No'),
      ),
      '#required' => TRUE,
  );
  $form['submit'] = array(
          '#type' => 'submit',
          '#value' => 'submit',
  );
  return $form;
}

function quiz1_form_submit($form, &$form_state) {
  $fruit = $form_state['values']['fruit'];
  $_SESSION['fruit'] = $fruit;
  $form_state['redirect'] = 'quiz_question_2';
}

function quiz2_form_submit($form, &$form_state) {
  $chocolate = $form_state['values']['chocolate'];
  $_SESSION['chocolate'] = $chocolate;
  $form_state['redirect'] = 'quiz_question_3';
}

function quiz3_form_submit($form, &$form_state) {
  $gluten = $form_state['values']['gluten'];
  $_SESSION['gluten'] = $gluten;
  $form_state['redirect'] = 'quiz_results';
}

function quiz_success() {
  $gluten = $_SESSION['values']['gluten'];
  $cherries = $_SESSION['values']['cherries'];
  $chocolate = $_SESSION['values']['chocolate'];
  var_dump($gluten);
  if ($gluten === 'No') {
    return '<p>Get a donut!</p>';
  } else {
    return "<p>Cool! we've got stuff for you too!</p>";
  }
}
