<?php

// TO DO:
// 1. fix everything
// 2. write at least two more questions
// 3. make suggestions based on questions

function pastry_quiz_menu() {
    $items['quiz'] = array(
        'title' => 'What should I eat!?',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('start_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['quiz_question_1'] = array(
        'page callback' => 'drupal_get_form',
        'page arguments' => array('one_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['quiz_question_2'] = array(
        'page callback' => 'drupal_get_form',
        'page arguments' => array('two_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['quiz_question_3'] = array(
        'page callback' => 'drupal_get_form',
        'page arguments' => array('three_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['quiz_success'] = array(
        'title' => 'Quiz Results!',
        'page callback' => 'quiz_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function start_form() {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
  );

  return $form;
}

function start_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'quiz_question_1';
}


//********** Question one ****************

function one_form() {
  $form['gluten'] = array(
      '#title' => 'Gluten Intollerance',
      '#type' => 'radios',
      '#description' => t('Are you gluten intolerant?'),
      '#options' => array(
          'yes' => t('Yes!'),
          'no' => t('No, bring on the carbs!'),
      ),
      '#required' => TRUE,
  );

  $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'submit',
    );

  return $form;
}

function one_form_submit($form, &$form_state) {
  $gluten = $form_state['values']['gluten'];
  $gluten_answer = null;

  $_SESSION['gluten'] = $gluten_answer;
  $form_state['redirect'] = 'quiz_question_2';
}

//********** Question two ****************

function two_form() {
  $form['sweet'] = array(
      '#title' => 'Sweet Tooth',
      '#type' => 'radios',
      '#description' => t('Do you like sweet pastries?'),
      '#options' => array(
        'yes' => t('Yes, I cant get enough!'),
        'no' => t('No, I prefer other flavors.'),
      ),
      '#required' => TRUE,
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
  );

  return $form;
}

function two_form_submit($form, &$form_state) {
  $sweet = $form_state['values']['sweet'];
  $sweet_answer = null;

  $_SESSION['sweet'] = $sweet_answer;
  $form_state['redirect'] = 'quiz_question_3';
}

//********** Question three ****************

function three_form() {
  $form['savory'] = array(
      '#title' => 'Savory Treats',
      '#type' => 'radios',
      '#description' => t('Do you like savory pastries (like: meat pies)?'),
      '#options' => array(
        'yes' => t('Yes, I love savory foods!'),
        'no' => t('No, I prefer other flavors.'),
      ),
      '#required' => TRUE,
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
  );

  return $form;
}

function three_form_submit($form, &$form_state) {
  $savory = $form_state['values']['savory'];
  $savory_answer = null;

  $_SESSION['savory'] = $savory_answer;
  $form_state['redirect'] = 'quiz_success';
}


function quiz_success() {
  // $quiz_ouput = $_SESSION['test_result'];
  // return '<p>' . $quiz_ouput . '</p>';
  return "quiz sucess page obtained!";
}
