<?php
function bakery_user_menu() {
    $items['welcome'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['goodbye'] = array(
        'title' => 'Come back soon!',
        'page callback' => 'goodbye_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function bakery_user_user_login(&$edit, $account) {
    $_GET['destination'] = 'welcome';
}

function welcome_user() {
    return "<p>Welcome to Cameron's Bakery!</p>";
}

function bakery_user_user_logout(&$edit, $account) {
    $_GET['destination'] = 'goodbye';
}

function goodbye_user() {
    return "<p>Thank you for visiting!</p>";
}
