<?php
function bakery_user_menu() {
    $items['welcome'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['goodbye'] = array(
        'title' => 'Goodbye for now',
        'page callback' => 'goodbye_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function bakery_user_user_login() {
    $_GET['destination'] = 'welcome';
}

function bakery_user_user_logout() {
    $_GET['destination'] = 'goodbye';
}

function welcome_page() {
    return "<p>Welcome to Cameron's Bakery!</p>";
}

function goodbye_page() {
    return "<p>Glad you stopped by, Hope to see you soon!</p>";
}
