<?php

    function custom_comment_submit_form_alter(&$form, &$form_state, $form_id) {
        /*
        print('<pre>');
        print_r($form_id);
        print('</pre>');
        */

        if ($form_id == 'comment_node_article_form') {
            /*
             * print('<pre>');
             * print_r($form);
             * print('</pre>');
             */

           $form['subject']['#access'] = 0; 
        } 
    }
