<?php
function bakerylogin_menu() {
    $items['welcome'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function bakerylogin_user_login(&$edit, $account) {
    $_GET['destination'] = 'welcome';
}

function welcome_user() {
    return "<p>Welcome to Cameron's Bakery!</p>";
}
